Full Ruby client (exchange_code)
civic-community/civic-sip-api-ruby pull request #1
Opened 2018-05-05 02:38 UTC by jimryan

Hey all,

I've written the full Ruby library, with tests and wrote documentation.  I copied a lot of the README from the PHP project (hope that's alright) - I thought it made sense that the various clients have similar documentation, adapted for the specific language.

I have _not_ released the gem yet - I wasn't sure if you wanted me to do that.  I am happy to release it if you'd like, and add whoever you'd like as a maintainer.  `civic_sip` is available, so that's what I used in the README.

The only thing missing from the REQUIREMENTS is the PoC page.  What do you think would be the best way to demo this? 

Please let me know if there are any changes or improvements you'd like.

This will be used in a production application in a few weeks, and I will continue improving it if any issues arise.

Here is my ETH address for the bounty: 0xeC9F7845ab14d3766c9Fc77Df4BC01429F251B0a

Thanks for Civic - it's been a great developer and user experience!

2018-07-31 15:49 UTC, jimryan commented
I just wanted to check up on this.  I've been using it in a production application for these past couple of months with success, so I'm confident that the library works well.  If there's anything that I can do to help move this along, please let me know - I'm happy to make changes.  I'd love to get this released for the Ruby community.

2018-07-31 20:26 UTC, slaphead commented
Hi @jimryan,

Apologies for the slowness on this. We will get back to you asap. Glad to hear it is working well on your prod environment. We still have to go over the code, but plan to do this as soon as possible.

2018-09-07 04:20 UTC, trappist commented
Assuming if Civic had a Ruby guy you would have developed this internally instead of issuing a bounty, I'll weigh in as a Ruby guy who just barely found this before attempting to claim the bounty myself.

It's very nicely done. It's done The Ruby Way™. The code is organized the way a Ruby developer would expect, so the methods I'm looking for are easy to find, and well documented where appropriate without being overly verbose. The documentation in the README made it straightforward to use.

My first attempt at using it for my integration didn't work, but only (I think) because I tried to exchange an old token - my second attempt with the same code, but a new token, worked perfectly. I imagine this library would have made that more clear if possible, but it did all it could - raised a helpful exception with the server's HTTP code (400) and the body of its response: "token failed verification". Would have been helpful to see "token expired" or something, assuming that was the problem, but there's no way for the library to have made that distinction.

If this were my bounty I'd award it.

2018-09-07 15:16 UTC, jimryan commented
Thank you for the support and kind words, @trappist.  I too hope that Civic will one day review my PR and award me the bounty.  

If you have any questions or run into any difficulties using the library, feel free to reach out.

2018-10-05 03:53 UTC, amit-dhoundiyal commented
Hi @jimryan 
I Have  not Found the civic_sip gem anywhere and i want to integrate civic with my rails project and i don't found anything can you please Help me to figure it out from this Problem. 
Thanks

2018-10-05 04:46 UTC, trappist commented
@amit-dhoundiyal put this in your project's Gemfile:
```ruby
gem 'civic_sip', github: 'jimryan/civic-sip-api-ruby'
```

2018-11-21 21:39 UTC, slaphead requested changes
Hi Jim,

We got a review done and thank you for your patience on this!

There is only one small non-functional change. The way it was setup, it didn't load the helper files into the tests so they were failing although the tests themselves are actually correct. This can be remedied by including a file at the root of the library named .rspec with the contents of --require spec_helper

Once this small part is done, this is all good.

2018-11-21 22:44 UTC, jimryan commented
Hey @slaphead - Sorry about that!  Not sure how I forgot to commit that.  I just added it.

2018-11-22 15:06 UTC, slaphead commented
That was quick. Thank you! I am informing internally about the updates and we will be in touch with you.

2019-03-26 18:57 UTC, slaphead approved these changes

2019-03-26 18:58 UTC, merged